/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Wed Jul 27 21:42:12 2016. */

#include "riemann.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t State_fields[9] = {
    PB_FIELD(  1, INT64   , OPTIONAL, STATIC  , FIRST, State, time, time, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, State, state, time, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, State, service, state, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, OTHER, State, host, service, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, State, description, host, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, State, once, description, 0),
    PB_FIELD(  7, STRING  , REPEATED, CALLBACK, OTHER, State, tags, once, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, State, ttl, tags, 0),
    PB_LAST_FIELD
};

const pb_field_t Event_fields[12] = {
    PB_FIELD(  1, INT64   , OPTIONAL, STATIC  , FIRST, Event, time, time, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, Event, state, time, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, Event, service, state, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, CALLBACK, OTHER, Event, host, service, 0),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, Event, description, host, 0),
    PB_FIELD(  7, STRING  , REPEATED, CALLBACK, OTHER, Event, tags, description, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, Event, ttl, tags, 0),
    PB_FIELD(  9, MESSAGE , REPEATED, CALLBACK, OTHER, Event, attributes, ttl, &Attribute_fields),
    PB_FIELD( 13, SINT64  , OPTIONAL, STATIC  , OTHER, Event, metric_sint64, attributes, 0),
    PB_FIELD( 14, DOUBLE  , OPTIONAL, STATIC  , OTHER, Event, metric_d, metric_sint64, 0),
    PB_FIELD( 15, FLOAT   , OPTIONAL, STATIC  , OTHER, Event, metric_f, metric_d, 0),
    PB_LAST_FIELD
};

const pb_field_t Query_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, CALLBACK, FIRST, Query, string, string, 0),
    PB_LAST_FIELD
};

const pb_field_t Msg_fields[6] = {
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , FIRST, Msg, ok, ok, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, Msg, error, ok, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, Msg, states, error, &State_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, Msg, query, states, &Query_fields),
    PB_FIELD(  6, MESSAGE , REPEATED, CALLBACK, OTHER, Msg, events, query, &Event_fields),
    PB_LAST_FIELD
};

const pb_field_t Attribute_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, Attribute, key, key, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, CALLBACK, OTHER, Attribute, value, key, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Event, attributes) < 65536 && pb_membersize(Msg, states) < 65536 && pb_membersize(Msg, query) < 65536 && pb_membersize(Msg, events) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_State_Event_Query_Msg_Attribute)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Event, attributes) < 256 && pb_membersize(Msg, states) < 256 && pb_membersize(Msg, query) < 256 && pb_membersize(Msg, events) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_State_Event_Query_Msg_Attribute)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
